In [1]:
import pandas as pd

In [4]:
data = pd.read_parquet('../data/us_10m_nointernship_ai_skills_benefits.parquet.gzip')

In [5]:
dates = pd.read_parquet('../data/US_10M_POSTS_DATES.parquet.gzip')

In [6]:
data = data.merge(dates, on='ID', how = 'left')

In [7]:
data[data['EXPIRED'].isna()]

Empty DataFrame
Columns: [ID, CITY_NAME, COUNTY_NAME, STATE_NAME, NAICS_2022_2, NAICS_2022_2_NAME, MIN_EDULEVELS_NAME, EMPLOYMENT_TYPE, EMPLOYMENT_TYPE_NAME, IS_INTERNSHIP, REMOTE_TYPE, REMOTE_TYPE_NAME, SKILLS, SKILLS_NAME, POSTED, LAST_UPDATED_DATE, ONET, ONET_NAME, ONET_2019, ONET_2019_NAME, SOC_2021_2_NAME, SOC_2021_2, MIN_YEARS_EXPERIENCE, COMPANY, COMPANY_NAME, COMPANY_RAW, AI ROLE, wfh_wham_prob, wfh_wham, YEAR, EDU_ASSISTANCE, WLB, PAID_LEAVE, HEALTH_WELLBEING, PARENTAL_LEAVE, CULTURE, EXPERIENCE_BUCKET, SALARY, LOG_SALARY, EXPIRED, DURATION]
Index: []

[0 rows x 41 columns]

In [8]:
len(data)

11581326

In [9]:
data[data['DURATION'].isna()]

,ID,CITY_NAME,COUNTY_NAME,STATE_NAME,NAICS_2022_2,NAICS_2022_2_NAME,MIN_EDULEVELS_NAME,EMPLOYMENT_TYPE,EMPLOYMENT_TYPE_NAME,IS_INTERNSHIP,...,WLB,PAID_LEAVE,HEALTH_WELLBEING,PARENTAL_LEAVE,CULTURE,EXPERIENCE_BUCKET,SALARY,LOG_SALARY,EXPIRED,DURATION
0,b5e9360ab429758bc6e8e259fcf66234d3163dcf,"Brentwood, TN","Williamson, TN",Tennessee,62,Health Care and Social Assistance,Master's degree,1,Full-time (> 32 hours),False,...,True,True,True,False,False,6-10 years,NaN,NaN,2020-02-05,NaN
1,eff8c5c87b50735a4684ebc33d41d1b36ff46aa8,"Smyrna, TN","Rutherford, TN",Tennessee,72,Accommodation and Food Services,High school or GED,1,Full-time (> 32 hours),False,...,False,False,False,False,False,None Listed,NaN,NaN,2020-03-07,NaN
2,b8b974adf881aa6c934392d71ad46dff810dcb34,"Denver, CO","Denver, CO",Colorado,52,Finance and Insurance,Bachelor's degree,1,Full-time (> 32 hours),False,...,False,False,False,False,False,3-5 years,NaN,NaN,2020-02-04,NaN
4,1513ec98d6d7b3ffda588c9834a9ac2e47f8921b,"Plano, TX","Collin, TX",Texas,31,Manufacturing,Bachelor's degree,1,Full-time (> 32 hours),False,...,False,False,False,False,False,3-5 years,NaN,NaN,2020-02-27,NaN
7,76eda7de4238503b2f9a21af8a51f1b43916c5f9,"Gretna, LA","Jefferson, LA",Louisiana,72,Accommodation and Food Services,High school or GED,1,Full-time (> 32 hours),False,...,False,False,False,False,False,None Listed,NaN,NaN,2020-04-02,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11581321,623fbd0258922f47db0dc616a5e2754f91a65685,"Houston, TX","Harris, TX",Texas,62,Health Care and Social Assistance,High school or GED,1,Full-time (> 32 hours),False,...,True,True,False,False,False,1-2 years,NaN,NaN,2021-05-07,NaN
11581322,b6e4667b5eefe314c009c1809404834d37a80ce0,"Atlanta, GA","Fulton, GA",Georgia,31,Manufacturing,Bachelor's degree,1,Full-time (> 32 hours),False,...,False,False,False,False,True,None Listed,NaN,NaN,2021-03-15,NaN
11581323,0fbd0a7227f24b8e665649acb79f3c1772b7cf46,"Hauppauge, NY","Suffolk, NY",New York,56,Administrative and Support and Waste Managemen...,No Education Listed,1,Full-time (> 32 hours),False,...,False,False,False,False,False,1-2 years,43680.0,10.684646,2021-03-10,NaN
11581324,df22cd59c119ecea024e4445f37a03f0b1540345,"Lynbrook, NY","Nassau, NY",New York,54,"Professional, Scientific, and Technical Services",Bachelor's degree,1,Full-time (> 32 hours),False,...,False,False,False,False,False,None Listed,NaN,NaN,2021-03-16,NaN
11581325,060d09035f9dd9ba5b1b08a236573d8cedf17c01,"Fargo, ND","Cass, ND",North Dakota,62,Health Care and Social Assistance,High school or GED,2,Part-time (≤ 32 hours),False,...,True,True,False,False,False,None Listed,NaN,NaN,2021-04-04,NaN

In [13]:
# get EXPIRED data type
data['EXPIRED'] = pd.to_datetime(data['EXPIRED'])

In [14]:
data['POSTED'] = pd.to_datetime(data['POSTED'])

In [15]:
data['DURATION_CALC'] = data['EXPIRED'] - data['POSTED']

In [16]:
data['DURATION_CALC']

0           62 days
1           93 days
2           61 days
3           59 days
4           84 days
             ...
11581321   119 days
11581322    66 days
11581323    61 days
11581324    67 days
11581325    86 days
Name: DURATION_CALC, Length: 11581326, dtype: timedelta64[ns]

In [17]:
data['DURATION_CALC'].describe()

count                      11581326
mean     59 days 08:43:06.190078755
std      26 days 16:04:52.115791118
min                 0 days 00:00:00
25%                43 days 00:00:00
50%                61 days 00:00:00
75%                69 days 00:00:00
max               120 days 00:00:00
Name: DURATION_CALC, dtype: object

In [18]:
data.to_parquet('../data/us_10m_nointernship_ai_skills_benefits.parquet.gzip', compression='gzip')