%share of AI roles with perk X = %share of perk X in general + %share of AI roles + log(size of occupation-year) + log(salary of AI roles)

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
from IPython.core.display import HTML

In [10]:
import numpy as np

In [2]:
# import stargazer
from stargazer.stargazer import Stargazer

In [3]:
import sys
import os

# Add parent directory to sys.path
parent_dir = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
sys.path.append(parent_dir)

In [4]:
from package_files.benefits_defns import *

In [5]:
df = pd.read_csv('../exports/occ_year_coeff_analysis.csv')

In [6]:
pd.set_option('display.max_columns', None)

In [8]:
df[(df['Occupation']=="Architecture and Engineering Occupations") & (df['Year']==2019)]

,Benefit,Occupation,Year,AI Coefficient,Error,P-Value,SOC_2021_2_NAME,YEAR,AI Demand,AI Demand % Change,PRIOR YEAR % CHANGE,LOG_SALARY_ai,SALARY_ai,LOG_SALARY_non_ai,SALARY_non_ai,Salary (Log) Premium,SALARY_PREMIUM,DURATION_CALC_ai,DURATION_CALC_non_ai,MEAN SALARY,job_count,Prevalence: Tuition Assistance,Prevalence: Tuition Assistance (AI),Prevalence: Tuition Assistance (Non-AI),Prevalence: Paid Leave,Prevalence: Paid Leave (AI),Prevalence: Paid Leave (Non-AI),Prevalence: Health and Wellbeing,Prevalence: Health and Wellbeing (AI),Prevalence: Health and Wellbeing (Non-AI),Prevalence: Parental Leave,Prevalence: Parental Leave (AI),Prevalence: Parental Leave (Non-AI),Prevalence: Workplace Culture,Prevalence: Workplace Culture (AI),Prevalence: Workplace Culture (Non-AI),Prevalence: Remote Work,Prevalence: Remote Work (AI),Prevalence: Remote Work (Non-AI)
0,EDU_ASSISTANCE,Architecture and Engineering Occupations,2019,-0.378773,0.202133,0.061,Architecture and Engineering Occupations,2019,2.031486,24.871731,NaN,11.443344,97865.619048,11.108535,73760.300943,103.013976,132.680612,61.510441,59.027063,73966.078049,42432,4.645079,3.016241,4.678855,11.566742,8.236659,11.635795,3.113216,1.62413,3.144094,0.782428,1.972158,0.757758,5.56891,10.788863,5.460669,2.348773,3.415783,2.32633
90,WLB,Architecture and Engineering Occupations,2019,-0.155173,0.112814,0.169,Architecture and Engineering Occupations,2019,2.031486,24.871731,NaN,11.443344,97865.619048,11.108535,73760.300943,103.013976,132.680612,61.510441,59.027063,73966.078049,42432,4.645079,3.016241,4.678855,11.566742,8.236659,11.635795,3.113216,1.62413,3.144094,0.782428,1.972158,0.757758,5.56891,10.788863,5.460669,2.348773,3.415783,2.32633
180,PAID_LEAVE,Architecture and Engineering Occupations,2019,-0.303556,0.125737,0.016,Architecture and Engineering Occupations,2019,2.031486,24.871731,NaN,11.443344,97865.619048,11.108535,73760.300943,103.013976,132.680612,61.510441,59.027063,73966.078049,42432,4.645079,3.016241,4.678855,11.566742,8.236659,11.635795,3.113216,1.62413,3.144094,0.782428,1.972158,0.757758,5.56891,10.788863,5.460669,2.348773,3.415783,2.32633
270,HEALTH_WELLBEING,Architecture and Engineering Occupations,2019,-0.590114,0.272715,0.030,Architecture and Engineering Occupations,2019,2.031486,24.871731,NaN,11.443344,97865.619048,11.108535,73760.300943,103.013976,132.680612,61.510441,59.027063,73966.078049,42432,4.645079,3.016241,4.678855,11.566742,8.236659,11.635795,3.113216,1.62413,3.144094,0.782428,1.972158,0.757758,5.56891,10.788863,5.460669,2.348773,3.415783,2.32633
360,PARENTAL_LEAVE,Architecture and Engineering Occupations,2019,0.958254,0.256600,0.000,Architecture and Engineering Occupations,2019,2.031486,24.871731,NaN,11.443344,97865.619048,11.108535,73760.300943,103.013976,132.680612,61.510441,59.027063,73966.078049,42432,4.645079,3.016241,4.678855,11.566742,8.236659,11.635795,3.113216,1.62413,3.144094,0.782428,1.972158,0.757758,5.56891,10.788863,5.460669,2.348773,3.415783,2.32633
450,CULTURE,Architecture and Engineering Occupations,2019,0.568717,0.114443,0.000,Architecture and Engineering Occupations,2019,2.031486,24.871731,NaN,11.443344,97865.619048,11.108535,73760.300943,103.013976,132.680612,61.510441,59.027063,73966.078049,42432,4.645079,3.016241,4.678855,11.566742,8.236659,11.635795,3.113216,1.62413,3.144094,0.782428,1.972158,0.757758,5.56891,10.788863,5.460669,2.348773,3.415783,2.32633
540,wfh_wham,Architecture and Engineering Occupations,2019,0.366585,0.194626,0.060,Architecture and Engineering Occupations,2019,2.031486,24.871731,NaN,11.443344,97865.619048,11.108535,73760.300943,103.013976,132.680612,61.510441,59.027063,73966.078049,42432,4.645079,3.016241,4.678855,11.566742,8.236659,11.635795,3.113216,1.62413,3.144094,0.782428,1.972158,0.757758,5.56891,10.788863,5.460669,2.348773,3.415783,2.32633

In [7]:
df

,Benefit,Occupation,Year,AI Coefficient,Error,P-Value,SOC_2021_2_NAME,YEAR,AI Demand,AI Demand % Change,PRIOR YEAR % CHANGE,LOG_SALARY_ai,SALARY_ai,LOG_SALARY_non_ai,SALARY_non_ai,Salary (Log) Premium,SALARY_PREMIUM,DURATION_CALC_ai,DURATION_CALC_non_ai,MEAN SALARY,job_count,Prevalence: Tuition Assistance,Prevalence: Tuition Assistance (AI),Prevalence: Tuition Assistance (Non-AI),Prevalence: Paid Leave,Prevalence: Paid Leave (AI),Prevalence: Paid Leave (Non-AI),Prevalence: Health and Wellbeing,Prevalence: Health and Wellbeing (AI),Prevalence: Health and Wellbeing (Non-AI),Prevalence: Parental Leave,Prevalence: Parental Leave (AI),Prevalence: Parental Leave (Non-AI),Prevalence: Workplace Culture,Prevalence: Workplace Culture (AI),Prevalence: Workplace Culture (Non-AI),Prevalence: Remote Work,Prevalence: Remote Work (AI),Prevalence: Remote Work (Non-AI)
0,EDU_ASSISTANCE,Architecture and Engineering Occupations,2019,-0.378773,0.202133,0.061,Architecture and Engineering Occupations,2019,2.031486,24.871731,NaN,11.443344,97865.619048,11.108535,73760.300943,103.013976,132.680612,61.510441,59.027063,73966.078049,42432,4.645079,3.016241,4.678855,11.566742,8.236659,11.635795,3.113216,1.624130,3.144094,0.782428,1.972158,0.757758,5.568910,10.788863,5.460669,2.348773,3.415783,2.326330
1,EDU_ASSISTANCE,Architecture and Engineering Occupations,2021,-0.191725,0.140017,0.171,Architecture and Engineering Occupations,2021,2.278018,15.179062,-2.642404,11.521036,107050.060606,11.095518,73216.702324,103.835046,146.209891,61.420229,63.841780,73671.056972,42098,7.187990,5.839416,7.219427,20.221863,11.261731,20.430735,3.722267,2.294056,3.755560,2.598698,3.232534,2.583923,10.442301,24.400417,10.116921,8.357362,14.465409,8.215270
2,EDU_ASSISTANCE,Architecture and Engineering Occupations,2022,-0.309976,0.108110,0.004,Architecture and Engineering Occupations,2022,2.446456,7.394079,15.179062,11.600475,115932.657459,11.235284,83342.705232,103.250399,139.103545,54.149606,55.015043,83890.460953,57103,8.840166,6.800286,8.891322,22.760626,15.533286,22.941873,4.591703,2.219041,4.651205,3.991034,5.153901,3.961871,15.806525,35.146743,15.321509,14.685004,18.168605,14.597810
3,EDU_ASSISTANCE,Architecture and Engineering Occupations,2020,-0.152420,0.196615,0.438,Architecture and Engineering Occupations,2020,1.977806,-2.642404,24.871731,11.428493,100957.585366,11.075966,72630.480348,103.182813,139.001677,60.158371,59.307465,72858.029585,33522,5.271165,4.223228,5.292310,16.428017,9.502262,16.567759,2.890639,1.659125,2.915487,1.312571,1.357466,1.311665,6.691128,18.853695,6.445723,4.442167,13.698630,4.255188
4,EDU_ASSISTANCE,Architecture and Engineering Occupations,2018,0.043941,0.219785,0.842,Architecture and Engineering Occupations,2018,1.626858,NaN,NaN,11.279748,85233.255814,11.095357,72599.869117,101.661881,117.401390,64.000000,61.662382,72708.646776,40569,3.307944,3.333333,3.307525,8.255072,6.060606,8.291363,1.466637,1.818182,1.460823,0.276073,0.151515,0.278133,4.777047,7.121212,4.738280,0.000000,NaN,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,wfh_wham,Transportation and Material Moving Occupations,2019,-18.205488,17234.764550,0.999,Transportation and Material Moving Occupations,2019,0.033652,-18.600785,NaN,10.485831,38192.625000,10.591160,44183.609987,99.005500,86.440707,59.806452,61.214999,44182.104241,92120,4.829570,0.000000,4.831196,21.079027,12.903226,21.081780,3.222970,3.225806,3.222969,0.578593,0.000000,0.578788,2.248155,3.225806,2.247825,0.385060,0.000000,0.385194
611,wfh_wham,Transportation and Material Moving Occupations,2021,0.533101,0.527071,0.312,Transportation and Material Moving Occupations,2021,0.067199,149.616383,-20.001353,10.663532,48247.636364,10.664556,46919.891740,99.990403,102.829812,66.026549,65.484129,46920.261844,168157,7.579227,6.194690,7.580158,36.863764,11.504425,36.880817,7.994910,4.424779,7.997310,3.968315,5.309735,3.967413,5.318839,32.743363,5.300398,0.769559,3.539823,0.767678
612,wfh_wham,Transportation and Material Moving Occupations,2022,1.883420,0.299236,0.000,Transportation and Material Moving Occupations,2022,0.085570,27.338156,149.616383,10.630348,47164.969697,10.708293,48730.623684,99.272107,96.787125,56.700855,57.916970,48729.813507,136730,8.390990,6.837607,8.392320,36.712499,23.076923,36.724177,5.294376,4.273504,5.295250,6.326337,11.111111,6.322239,9.225481,29.059829,9.208494,0.806475,14.655172,0.794634
613,wfh_wham,Transportation and Material Moving Occupations,2020,-11.442227,437.577258,0.979,Transportation and Material Moving Occupations,2020,0.026921,-20.001353,-18.600785,10.529685,40678.900000,10.562795,42269.527535,99.686540,96.236940,55.210526,62.520019,42269.295590,141154,5.673945,5.263158,5.674055,29.072502,18.421053,29.075371,7.670346,2.631579,7.671703,1.370135,2.631579,1.369795,2.021905,5.263158,2.021032,0.565415,0.000000,0.565566
614,wfh_wham,Transportation and Material Moving Occupations,2023,0.597295,0.549521,0.277,Transportation and Material Moving Occupations,2023,0.075868,-11.338498,27.338156,10.932600,61059.333333,10.751517,51076.903562,101.684249,119.543921,48.523810,49.491282,51084.087750,110719,9.677652,10.714286,9.676865,40.470922,28.571429,40.479957,6.056774,5.952381,6.056854,6.511078,4.761905,6.512406,8.611891,21.428571,8.602160,0.889245,4.819277,0.886276

In [11]:
# add column for log job count
df['Log Job Count'] = df['job_count'].apply(lambda x: np.log(x))

%share of AI roles with perk X = %share of perk X in general + %share of AI roles + log(size of occupation-year) + log(salary of AI roles)

In [31]:
import statsmodels.api as sm
# benefit_models = {}
benefit_models = []
for benefit in benefits4:
    benefit_df = df[df['Benefit'] == benefit].copy()
    benefit_df.rename(columns={f'Prevalence: {benefits_labels_map[benefit]}': f'Overall Benefit Prevalence', 'LOG_SALARY_ai':'Mean Log AI Salary'}, inplace=True)

    label = benefits_labels_map[benefit]

    X = benefit_df[[f'Overall Benefit Prevalence', 'AI Demand', 'Log Job Count', 'Mean Log AI Salary']]
    y = benefit_df[f'Prevalence: {label} (AI)']

    # Add a constant to the independent variable
    X = sm.add_constant(X)

    # Fit the OLS model
    model = sm.OLS(y, X).fit()
    print(benefit)
    # benefit_models.setdefault(benefit, []).append(model)
    benefit_models.append(model)
    # Print the summary of the regression
    print(model.summary())

EDU_ASSISTANCE
                                     OLS Regression Results
===============================================================================================
Dep. Variable:     Prevalence: Tuition Assistance (AI)   R-squared:                       0.365
Model:                                             OLS   Adj. R-squared:                  0.335
Method:                                  Least Squares   F-statistic:                     12.23
Date:                                 Sun, 27 Oct 2024   Prob (F-statistic):           6.74e-08
Time:                                         20:13:36   Log-Likelihood:                -221.04
No. Observations:                                   90   AIC:                             452.1
Df Residuals:                                       85   BIC:                             464.6
Df Model:                                            4
Covariance Type:                             nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
const                          7.6452     11.271      0.678      0.499     -14.764      30.054
Overall Benefit Prevalence     0.7774      0.117      6.630      0.000       0.544       1.010
AI Demand                      0.3868      0.183      2.113      0.038       0.023       0.751
Log Job Count                 -0.6276      0.366     -1.714      0.090      -1.356       0.100
Mean Log AI Salary            -0.1020      0.908     -0.112      0.911      -1.907       1.703
==============================================================================
Omnibus:                        8.011   Durbin-Watson:                   1.161
Prob(Omnibus):                  0.018   Jarque-Bera (JB):                7.689
Skew:                           0.598   Prob(JB):                       0.0214
Kurtosis:                       3.788   Cond. No.                         634.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
PAID_LEAVE
                                 OLS Regression Results
=======================================================================================
Dep. Variable:     Prevalence: Paid Leave (AI)   R-squared:                       0.690
Model:                                     OLS   Adj. R-squared:                  0.675
Method:                          Least Squares   F-statistic:                     47.19
Date:                         Sun, 27 Oct 2024   Prob (F-statistic):           7.82e-21
Time:                                 20:13:36   Log-Likelihood:                -259.51
No. Observations:                           90   AIC:                             529.0
Df Residuals:                               85   BIC:                             541.5
Df Model:                                    4
Covariance Type:                     nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
const                        -26.1926     16.827     -1.557      0.123     -59.650       7.264
Overall Benefit Prevalence     0.6957      0.053     13.006      0.000       0.589       0.802
AI Demand                      0.4778      0.282      1.693      0.094      -0.083       1.039
Log Job Count                  0.0049      0.526      0.009      0.993      -1.041       1.050
Mean Log AI Salary             2.2492      1.378      1.632      0.106      -0.491       4.990
==============================================================================
Omnibus:                       14.752   Durbin-Watson:                   1.627
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               19.099
Skew:                          -0.785   Prob(JB):                     7.12e-05
Kurtosis:                       4.622   Cond. No.                         986.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
HEALTH_WELLBEING
                                      OLS Regression Results
=================================================================================================
Dep. Variable:     Prevalence: Health and Wellbeing (AI)   R-squared:                       0.244
Model:                                               OLS   Adj. R-squared:                  0.209
Method:                                    Least Squares   F-statistic:                     6.874
Date:                                   Sun, 27 Oct 2024   Prob (F-statistic):           7.65e-05
Time:                                           20:13:36   Log-Likelihood:                -220.78
No. Observations:                                     90   AIC:                             451.6
Df Residuals:                                         85   BIC:                             464.1
Df Model:                                              4
Covariance Type:                               nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
const                          0.7667     10.866      0.071      0.944     -20.838      22.372
Overall Benefit Prevalence     0.9250      0.199      4.657      0.000       0.530       1.320
AI Demand                     -0.0448      0.177     -0.253      0.801      -0.398       0.308
Log Job Count                 -0.8212      0.340     -2.412      0.018      -1.498      -0.144
Mean Log AI Salary             0.8326      0.889      0.937      0.352      -0.935       2.600
==============================================================================
Omnibus:                       44.483   Durbin-Watson:                   2.041
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              124.559
Skew:                           1.725   Prob(JB):                     8.96e-28
Kurtosis:                       7.616   Cond. No.                         585.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
PARENTAL_LEAVE
                                   OLS Regression Results
===========================================================================================
Dep. Variable:     Prevalence: Parental Leave (AI)   R-squared:                       0.706
Model:                                         OLS   Adj. R-squared:                  0.692
Method:                              Least Squares   F-statistic:                     51.08
Date:                             Sun, 27 Oct 2024   Prob (F-statistic):           7.63e-22
Time:                                     20:13:36   Log-Likelihood:                -203.87
No. Observations:                               90   AIC:                             417.7
Df Residuals:                                   85   BIC:                             430.2
Df Model:                                        4
Covariance Type:                         nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
const                        -13.8560      9.321     -1.487      0.141     -32.388       4.676
Overall Benefit Prevalence     1.5792      0.124     12.784      0.000       1.334       1.825
AI Demand                     -0.0241      0.147     -0.164      0.870      -0.316       0.267
Log Job Count                  0.0511      0.280      0.183      0.856      -0.506       0.608
Mean Log AI Salary             1.1633      0.767      1.517      0.133      -0.362       2.688
==============================================================================
Omnibus:                       39.256   Durbin-Watson:                   1.759
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              235.330
Skew:                           1.124   Prob(JB):                     7.92e-52
Kurtosis:                      10.596   Cond. No.                         599.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
CULTURE
                                    OLS Regression Results
==============================================================================================
Dep. Variable:     Prevalence: Workplace Culture (AI)   R-squared:                       0.678
Model:                                            OLS   Adj. R-squared:                  0.663
Method:                                 Least Squares   F-statistic:                     44.82
Date:                                Sun, 27 Oct 2024   Prob (F-statistic):           3.45e-20
Time:                                        20:13:36   Log-Likelihood:                -282.82
No. Observations:                                  90   AIC:                             575.6
Df Residuals:                                      85   BIC:                             588.1
Df Model:                                           4
Covariance Type:                            nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
const                         61.6458     23.553      2.617      0.010      14.817     108.475
Overall Benefit Prevalence     2.1329      0.167     12.769      0.000       1.801       2.465
AI Demand                     -0.5748      0.354     -1.624      0.108      -1.279       0.129
Log Job Count                 -1.0695      0.683     -1.565      0.121      -2.428       0.289
Mean Log AI Salary            -4.3580      1.947     -2.238      0.028      -8.229      -0.487
==============================================================================
Omnibus:                       15.062   Durbin-Watson:                   1.591
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               23.777
Skew:                           0.694   Prob(JB):                     6.87e-06
Kurtosis:                       5.101   Cond. No.                         707.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
wfh_wham
                                 OLS Regression Results
========================================================================================
Dep. Variable:     Prevalence: Remote Work (AI)   R-squared:                       0.594
Model:                                      OLS   Adj. R-squared:                  0.571
Method:                           Least Squares   F-statistic:                     25.58
Date:                          Sun, 27 Oct 2024   Prob (F-statistic):           4.40e-13
Time:                                  20:13:36   Log-Likelihood:                -260.58
No. Observations:                            75   AIC:                             531.2
Df Residuals:                                70   BIC:                             542.7
Df Model:                                     4
Covariance Type:                      nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
const                         -7.3441     35.783     -0.205      0.838     -78.712      64.023
Overall Benefit Prevalence     1.5241      0.176      8.675      0.000       1.174       1.875
AI Demand                     -2.2066      0.590     -3.741      0.000      -3.383      -1.030
Log Job Count                  2.8565      1.044      2.736      0.008       0.774       4.939
Mean Log AI Salary            -1.5334      3.157     -0.486      0.629      -7.829       4.763
==============================================================================
Omnibus:                       30.435   Durbin-Watson:                   2.201
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               74.984
Skew:                           1.315   Prob(JB):                     5.22e-17
Kurtosis:                       7.133   Cond. No.                         728.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

# Display Results

In [27]:
stargazer = Stargazer(benefit_models)
display(HTML(stargazer.render_html()))

In [33]:
from stargazer.stargazer import Stargazer
from IPython.display import display, HTML

# Assume benefit_models is a list of models aligned with benefits4
stargazer = Stargazer(benefit_models)

# Set custom column labels based on benefit names
stargazer.custom_columns(benefits4_labels, [1] * len(benefits4))  # `[1] * len(benefits4)` specifies that each label is for one column

with open(f'../exports/occ_year_final_model.tex', 'w') as f:
    f.write(stargazer.render_latex())
# Render the HTML display with benefit names as model titles
display(HTML(stargazer.render_html()))

In [21]:

# Ensure benefit_models is aligned with benefits4 in the same order
models_with_titles = []
for benefit, model in zip(benefits4, benefit_models):
    model_title = f"Regression Model for {benefit}"
    model.title = model_title
    models_with_titles.append(model)

# Use Stargazer to display the models with titles
stargazer = Stargazer(models_with_titles)
display(HTML(stargazer.render_html()))

In [17]:
# for benefit in benefits4:
#     stargazer = Stargazer(benefit_models[benefit])
#     stargazer.title(f'Coefficients for {benefits_labels_map[benefit]}')
#     display(HTML(stargazer.render_html()))
#     # # export to latex
#     # with open(f'../exports/occ_year_coeff_{benefit}.tex', 'w') as f:
#     #     f.write(stargazer.render_latex())