In [2]:
import pandas as pd

In [3]:
posts_df = pd.read_csv('/Users/alejandracastaneda/Documents/Backup/beyond-salary-mb/data/OII_US_10M_POSTS_MAY26_SUBSAMPLE.csv')

In [5]:
pd.set_option('display.max_columns', None)  # Show all columns

In [6]:
posts_df.head()

,ID,POSTED,TITLE_RAW,COMPANY,COMPANY_NAME,MIN_EDULEVELS_NAME,EMPLOYMENT_TYPE_NAME,MIN_YEARS_EXPERIENCE,SALARY,REMOTE_TYPE_NAME,CITY_NAME,STATE_NAME,NAICS_2022_6,NAICS_2022_6_NAME,ONET,ONET_NAME,BENEFIT_NAME,BENEFIT_SUBCATEGORY_NAME,BENEFIT_CATEGORIES_NAME,YEAR,QUARTER
0,cc25bf7987491446b2c7f735c28c65605df5fc61,2021-11-30,Senior Medical Review Nurse Analyst (RN),99495737,WPS Health,Bachelor's degree,Full-time (> 32 hours),4.0,NaN,Remote,"Jacksonville, FL",Florida,524114,Direct Health and Medical Insurance Carriers,29-1141.00,Registered Nurses,"[\n ""Paid Time Off (PTO)"",\n ""401(k) Plans"",...","[\n ""Paid Time Off (PTO)"",\n ""401(k) Plans"",...","[\n ""Paid Leave"",\n ""Retirement and Savings""...",2021,4
1,f31e97e70d4dede03a6598532ad915a13755ecf0,2021-11-30,Senior Product Owner - Medicaid/LTSS,6915630,Humana,Bachelor's degree,Full-time (> 32 hours),5.0,NaN,[None],"Jersey City, NJ",New Jersey,524114,Direct Health and Medical Insurance Carriers,15-1299.09,Information Technology Project Managers,[],[],[],2021,4
2,b625146166c02402312a679240abb908cd113c15,2022-05-10,"Clinical Supervisor, Substance Use Disorders -...",37614618,Central City Concern,No Education Listed,Full-time (> 32 hours),5.0,100000.0,[None],"Portland, OR",Oregon,624190,Other Individual and Family Services,11-9111.00,Medical and Health Services Managers,"[\n ""Paid Time Off (PTO)"",\n ""403(b) Tax-She...","[\n ""Paid Time Off (PTO)"",\n ""403(b) Tax-She...","[\n ""Paid Leave"",\n ""Retirement and Savings""...",2022,2
3,948882b652a32dfe2f2cf3dec27d3690181ac30a,2022-05-10,Seasonal Landscaper,41454246,HEI Hotels & Resorts,No Education Listed,Full-time (> 32 hours),NaN,NaN,[None],"Waltham, MA",Massachusetts,721110,Hotels (except Casino Hotels) and Motels,37-3011.00,Landscaping and Groundskeeping Workers,"[\n ""401(k) Plans"",\n ""Vision Insurance"",\n ...","[\n ""401(k) Plans"",\n ""Vision Insurance"",\n ...","[\n ""Retirement and Savings"",\n ""Insurance"",...",2022,2
4,a61e73a98166933c51df646c2181852954124070,2022-05-10,Endoscopy Registered Nurse PRN,39850046,St. David's Healthcare Partnership,Associate degree,Full-time (> 32 hours),1.0,NaN,[None],"Austin, TX",Texas,622110,General Medical and Surgical Hospitals,29-1141.00,Registered Nurses,"[\n ""Paid Time Off (PTO)"",\n ""401(k) Plans"",...","[\n ""Paid Time Off (PTO)"",\n ""401(k) Plans"",...","[\n ""Paid Leave"",\n ""Retirement and Savings""...",2022,2

In [30]:
posts_df['BENEFIT_CATEGORIES_NAME'].value_counts()

BENEFIT_CATEGORIES_NAME
[]                                                                                                                                                                                                                                                                                   50501
[\n  "Work-Life Balance"\n]                                                                                                                                                                                                                                                           3466
[\n  "Education and Career Development"\n]                                                                                                                                                                                                                                            1997
[\n  "Supplemental Pay"\n]                                                                                                                                                                                                                                                            1648
[\n  "Paid Leave"\n]                                                                                                                                                                                                                                                                  1285
                                                                                                                                                                                                                                                                                     ...
[\n  "Paid Leave",\n  "Paid Leave",\n  "Paid Leave",\n  "Retirement and Savings",\n  "Health and Wellness Benefits",\n  "Insurance",\n  "Insurance",\n  "Insurance",\n  "Insurance"\n]                                                                                                   1
[\n  "Education and Career Development",\n  "Retirement and Savings",\n  "Supplemental Pay",\n  "Insurance",\n  "Insurance",\n  "Insurance",\n  "Insurance",\n  "Insurance"\n]                                                                                                           1
[\n  "Paid Leave",\n  "Paid Leave",\n  "Retirement and Savings",\n  "Education and Career Development",\n  "Retirement and Savings",\n  "Insurance",\n  "Insurance",\n  "Other Benefits"\n]                                                                                              1
[\n  "Paid Leave",\n  "Education and Career Development",\n  "Insurance",\n  "Work-Life Balance",\n  "Work-Life Balance"\n]                                                                                                                                                              1
[\n  "Paid Leave",\n  "Paid Leave",\n  "Paid Leave",\n  "Education and Career Development",\n  "Retirement and Savings",\n  "Retirement and Savings",\n  "Supplemental Pay",\n  "Health and Wellness Benefits",\n  "Insurance",\n  "Insurance",\n  "Insurance",\n  "Insurance"\n]        1
Name: count, Length: 4782, dtype: int64

In [32]:
posts_df['BENEFIT_SUBCATEGORY_NAME'].value_counts()

BENEFIT_SUBCATEGORY_NAME
[]                                                                                                                                                                                                                       50501
[\n  "Flexible Work Schedules"\n]                                                                                                                                                                                         3027
[\n  "Bonuses/Stipends"\n]                                                                                                                                                                                                1521
[\n  "Professional Development"\n]                                                                                                                                                                                        1296
[\n  "401(k) Plans"\n]                                                                                                                                                                                                    1016
                                                                                                                                                                                                                         ...
[\n  "401(k) Plans",\n  "Professional Development",\n  "Bonuses/Stipends",\n  "Flexible Work Schedules",\n  "Discounts/Reimbursements"\n]                                                                                    1
[\n  "Paid Time Off (PTO)",\n  "Medical Leave",\n  "Financial Aid/Assistance",\n  "Professional Development",\n  "Other Retirement and Savings",\n  "Dental Insurance",\n  "Vision Insurance",\n  "Life Insurance"\n]        1
[\n  "Paid Time Off (PTO)",\n  "Sick Leave",\n  "401(k) Plans",\n  "Professional Development",\n  "Health Insurance",\n  "Relocation Assistance"\n]                                                                          1
[\n  "Paid Time Off (PTO)",\n  "401(k) Plans",\n  "Legal Services"\n]                                                                                                                                                        1
[\n  "Sick Leave",\n  "Flexible Work Schedules",\n  "Dental Insurance",\n  "Disability Insurance"\n]                                                                                                                         1
Name: count, Length: 9448, dtype: int64

In [7]:
skills_df = pd.read_csv('/Users/alejandracastaneda/Documents/Backup/beyond-salary-mb/data/OII_US_10M_SKILLS_MAY26_SUBSAMPLE.csv')

In [8]:
skills_df.head()

,ID,SKILL_ID,SKILL_NAME,SKILL_SUBCATEGORY_NAME,SKILL_CATEGORY_NAME
0,0fa8945cc2a78a1e40489ac0fcde084b894c7539,ES899BA440FA3441F22A,Workflow Management,Process Improvement and Optimization,Business
1,03b182f31e753fdcbc3b5fc9c6d6db7aed544882,KS1218W78FGVPVP2KXPX,Management,Business Management,Business
2,e02f4968e7b68084f737757b08667c439f11c06f,BGS8CFA33B3D9B49C56C,Concrete Forming,Concrete and Masonry,Architecture and Construction
3,0fa8945cc2a78a1e40489ac0fcde084b894c7539,BGSEE1E1C4671622F63B,Sales Support,Sales Management,Sales
4,610ec9ca254142cf3f3160d9688cf2f31e90e114,ES15B16B907D759C1EC2,Shipping And Receiving,General Shipping and Receiving,"Transportation, Supply Chain, and Logistics"

In [12]:
skills_df['SKILL_SUBCATEGORY_NAME'].value_counts()
# FIND SKILL SUBCATEGORY THAT CONTAINS AI
skills_df[skills_df['SKILL_SUBCATEGORY_NAME'].str.contains('AI', case=False, na=False)]['SKILL_SUBCATEGORY_NAME'].unique()

array(['Fundraising and Crowdsourcing', 'Promotions and Campaigns',
       'First Aid', 'Employee Training', 'Training Programs',
       'Vehicle Repair and Maintenance', 'Retail Sales',
       'Construction Painting', 'Roads and Drainage',
       'Equipment Repair and Maintenance', 'Supply Chain Management',
       'Facility Management and Maintenance',
       'General Repairs and Maintenance',
       'Artificial Intelligence and Machine Learning (AI/ML)',
       'Appliance Repair and Maintenance',
       'Insurance and Warranty Claims Processing', 'Rail Transportation',
       'Coaching and Athletic Training', 'Mainframe Technologies',
       'Air Quality and Emissions', 'Air Transportation',
       'Computer-Aided Manufacturing', 'Blockchain'], dtype=object)

In [25]:
pd.set_option('display.max_rows', 100)

In [ ]:
# filter skills to subcategory Artificial Intelligence and Machine Learning (AI/ML)
ai_ml_skills = skills_df[skills_df['SKILL_SUBCATEGORY_NAME'] == 'Artificial Intelligence and Machine Learning (AI/ML)']
ai_ml_skills['SKILL_NAME'].head(100)

1832                              Artificial Intelligence
1919                                     Machine Learning
2253                                              Chatbot
2273                               Intelligent Automation
2375                                     Machine Learning
2774                              Artificial Intelligence
2881                   Generative Artificial Intelligence
3349                                        Deep Learning
3350                                     Machine Learning
3650                                     Machine Learning
3789                              Artificial Intelligence
3924                                              Chatbot
3936                                  Supervised Learning
3939                                        Deep Learning
3946                                     Machine Learning
3947                              Artificial Intelligence
3952                                   Feature Extraction
3958                          Machine Learning Algorithms
6135                           Artificial Neural Networks
8585                                   Automation Systems
9880                              Artificial Intelligence
10854                             Artificial Intelligence
11362                  Generative Artificial Intelligence
12878                             Artificial Intelligence
18799                  Generative Artificial Intelligence
18800                                       Bot Framework
19140                             Artificial Intelligence
19417                             Artificial Intelligence
19421                                    Machine Learning
19551                  Generative Artificial Intelligence
19891                             Artificial Intelligence
20292                                    Machine Learning
21422                  Generative Artificial Intelligence
22303    Machine Learning Model Monitoring And Evaluation
23188                                    Machine Learning
23220                          Artificial Neural Networks
24723                                    Machine Learning
24729                                 Intelligent Control
25535                       Scikit-Learn (Python Package)
25682                                    Machine Learning
25684                         Machine Learning Algorithms
26219                                  Automation Systems
27161                                    Machine Learning
27618                                    Machine Learning
27683                                    Machine Learning
27721                              Text Retrieval Systems
30337                                    Machine Learning
30502                                       Deep Learning
30503                                    Machine Learning
30506                             Artificial Intelligence
30507                       Long Short-Term Memory (LSTM)
31653                             Artificial Intelligence
32954                                    Machine Learning
32969                             Artificial Intelligence
33107                                  Systems Automation
33339                                      Responsible AI
33410                                           Claude AI
33456                             Automated Data Cleaning
35624                   Automated Planning And Scheduling
35891                  Generative Artificial Intelligence
36012                             Artificial Intelligence
36881                              Text Retrieval Systems
37555                             Artificial Intelligence
37796                                    Machine Learning
38428                             Artificial Intelligence
40369                                    Machine Learning
40901                                    Machine Learning
41336                             Artificial Intelligence
41338                                    Machine Learning
45754                                    Machine Learning
46060                                             Chatbot
46307                                          Agentic AI
46322                                    Machine Learning
46458                             Artificial Intelligence
46955                             Artificial Intelligence
47170                                      Responsible AI
47181                              Intelligent Automation
47731                             Artificial Intelligence
47928                   Automated Planning And Scheduling
48096                                  Systems Automation
49247                          Data Version Control (DVC)
50492                                Cognitive Automation
52144                  Generative Artificial Intelligence
52912                                 Feature Engineering
54167                                    Machine Learning
54667                                  Systems Automation
55245                                    Machine Learning
55251                            Applied Machine Learning
56021                             Artificial Intelligence
56135                                    Machine Learning
56515                             Artificial Intelligence
57338                             Artificial Intelligence
57866                             Artificial Intelligence
58287                                    Machine Learning
58297                             Artificial Intelligence
58299                         Machine Learning Algorithms
58300                          Artificial Neural Networks
58519                             Artificial Intelligence
58522                                    Machine Learning
61287                                    Machine Learning
Name: SKILL_NAME, dtype: object

In [27]:
# check if the word prompt is in ai ml skills
ai_ml_skills[ai_ml_skills['SKILL_NAME'].str.contains('prompt', case=False, na=False)]['SKILL_NAME'].unique()

array(['Prompt Engineering'], dtype=object)

In [9]:
skills_df['SKILL_CATEGORY_NAME'].value_counts()

SKILL_CATEGORY_NAME
Physical and Inherent Abilities                191350
Business                                       154947
Health Care                                    151529
Information Technology                         146746
Media and Communications                       101959
Law, Regulation, and Compliance                 68278
Finance                                         64769
Sales                                           64436
Administration                                  59570
Customer and Client Support                     44284
Transportation, Supply Chain, and Logistics     39341
Maintenance, Repair, and Facility Services      33638
Analysis                                        31619
Marketing and Public Relations                  26111
Science and Research                            24430
Engineering                                     24386
Education and Training                          22845
Manufacturing and Production                    21002
Hospitality and Food Services                   18041
Architecture and Construction                   18039
Human Resources                                 14811
Public Safety and National Security             11835
Design                                           8079
Economics, Policy, and Social Studies            6961
Social and Human Services                        5085
Environment                                      4794
Energy and Utilities                             3934
Property and Real Estate                         2388
Agriculture, Horticulture, and Landscaping       1771
Performing Arts, Sports, and Recreation          1632
Personal Care and Services                       1415
Name: count, dtype: int64